package com.nekomimi.gankio.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.nekomimi.gankio.db.GankItem;

import com.nekomimi.gankio.db.GankItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gankItemDaoConfig;

    private final GankItemDao gankItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gankItemDaoConfig = daoConfigMap.get(GankItemDao.class).clone();
        gankItemDaoConfig.initIdentityScope(type);

        gankItemDao = new GankItemDao(gankItemDaoConfig, this);

        registerDao(GankItem.class, gankItemDao);
    }
    
    public void clear() {
        gankItemDaoConfig.getIdentityScope().clear();
    }

    public GankItemDao getGankItemDao() {
        return gankItemDao;
    }

}
