package com.nekomimi.gankio.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GANK_ITEM".
 */
public class GankItem {

    private Long id;
    /** Not-null value. */
    private String gankId;
    private java.util.Date createAt;
    private String Desc;
    private String publishedAt;
    private String type;
    /** Not-null value. */
    private String url;
    private String who;
    private Boolean used;

    public GankItem() {
    }

    public GankItem(Long id) {
        this.id = id;
    }

    public GankItem(Long id, String gankId, java.util.Date createAt, String Desc, String publishedAt, String type, String url, String who, Boolean used) {
        this.id = id;
        this.gankId = gankId;
        this.createAt = createAt;
        this.Desc = Desc;
        this.publishedAt = publishedAt;
        this.type = type;
        this.url = url;
        this.who = who;
        this.used = used;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getGankId() {
        return gankId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGankId(String gankId) {
        this.gankId = gankId;
    }

    public java.util.Date getCreateAt() {
        return createAt;
    }

    public void setCreateAt(java.util.Date createAt) {
        this.createAt = createAt;
    }

    public String getDesc() {
        return Desc;
    }

    public void setDesc(String Desc) {
        this.Desc = Desc;
    }

    public String getPublishedAt() {
        return publishedAt;
    }

    public void setPublishedAt(String publishedAt) {
        this.publishedAt = publishedAt;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public String getWho() {
        return who;
    }

    public void setWho(String who) {
        this.who = who;
    }

    public Boolean getUsed() {
        return used;
    }

    public void setUsed(Boolean used) {
        this.used = used;
    }

}
