package com.nekomimi.gankio.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.nekomimi.gankio.db.GankItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GANK_ITEM".
*/
public class GankItemDao extends AbstractDao<GankItem, Long> {

    public static final String TABLENAME = "GANK_ITEM";

    /**
     * Properties of entity GankItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property GankId = new Property(1, String.class, "gankId", false, "GANK_ID");
        public final static Property CreateAt = new Property(2, String.class, "createAt", false, "CREATE_AT");
        public final static Property Desc = new Property(3, String.class, "Desc", false, "DESC");
        public final static Property PublishedAt = new Property(4, String.class, "publishedAt", false, "PUBLISHED_AT");
        public final static Property Type = new Property(5, String.class, "type", false, "TYPE");
        public final static Property Url = new Property(6, String.class, "url", false, "URL");
        public final static Property Who = new Property(7, String.class, "who", false, "WHO");
        public final static Property Used = new Property(8, Boolean.class, "used", false, "USED");
    };


    public GankItemDao(DaoConfig config) {
        super(config);
    }
    
    public GankItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GANK_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"GANK_ID\" TEXT NOT NULL ," + // 1: gankId
                "\"CREATE_AT\" TEXT," + // 2: createAt
                "\"DESC\" TEXT," + // 3: Desc
                "\"PUBLISHED_AT\" TEXT," + // 4: publishedAt
                "\"TYPE\" TEXT," + // 5: type
                "\"URL\" TEXT NOT NULL ," + // 6: url
                "\"WHO\" TEXT," + // 7: who
                "\"USED\" INTEGER);"); // 8: used
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GANK_ITEM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GankItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getGankId());
 
        String createAt = entity.getCreateAt();
        if (createAt != null) {
            stmt.bindString(3, createAt);
        }
 
        String Desc = entity.getDesc();
        if (Desc != null) {
            stmt.bindString(4, Desc);
        }
 
        String publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindString(5, publishedAt);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
        stmt.bindString(7, entity.getUrl());
 
        String who = entity.getWho();
        if (who != null) {
            stmt.bindString(8, who);
        }
 
        Boolean used = entity.getUsed();
        if (used != null) {
            stmt.bindLong(9, used ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GankItem readEntity(Cursor cursor, int offset) {
        GankItem entity = new GankItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // gankId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // createAt
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Desc
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // publishedAt
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // type
            cursor.getString(offset + 6), // url
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // who
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0 // used
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GankItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGankId(cursor.getString(offset + 1));
        entity.setCreateAt(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDesc(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPublishedAt(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUrl(cursor.getString(offset + 6));
        entity.setWho(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUsed(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GankItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GankItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
